### ISSUE TITLE
puockNG以及原puock主题在前台提交ajax评论时并不会显示用户ua平台及ip，也不会显示用户评论等级，必须刷新网页才能显示，给出下面代码，希望修复bug

### ISSUE THREAD

**Issue by jd82k** [Lvshujun0918/Puock-NG#3]
echo '<div id="comment-' . get_comment_ID() . '" class="post-comment">
            <div class="info">
                <div>' . get_avatar($comment, 64, '', '', array('class' => 'md-avatar')) . '</div>
                <div class="ml-3 two-info">
                    <div class="puock-text ta3b">
                        <span class="t-md puock-links">' . get_comment_author_link($comment_id) . '</span>
                        ' . (pk_is_checked('comment_level') ? pk_the_author_class(false, $comment) : '') . '
                    </div>
                    <div class="t-sm c-sub">' . get_comment_date('Y-m-d H:i:s', $comment_id) . '</div>
                </div>
            </div>
            <div class="content">
                <div class="content-text t-md mt10 puock-text">
                    <p>' . get_comment_text($comment_id) . '</p>
                    ' . $comment_approved_str . '
                    <div class="comment-os c-sub">';
                
                if (pk_is_checked('comment_show_ua', true)):
                    $commentUserAgent = parse_user_agent($comment->comment_agent);
                    $commentOsIcon = pk_get_comment_ua_os_icon($commentUserAgent['platform']);
                    $commentBrowserIcon = pk_get_comment_ua_os_icon($commentUserAgent['browser']);
                    echo "<span class='mt10' title='{$commentUserAgent['platform']}'><i class='$commentOsIcon'></i>&nbsp;<span>{$commentUserAgent['platform']}&nbsp;</span></span>";
                    echo "<span class='mt10' title='{$commentUserAgent['browser']} {$commentUserAgent['version']}'><i class='$commentBrowserIcon'></i>&nbsp;<span>{$commentUserAgent['browser']}</span></span>";
                endif;
                ?>
                <?php
                if (pk_is_checked('comment_show_ip', true)) {
                    if (!pk_is_checked('comment_dont_show_owner_ip') || (pk_is_checked('comment_dont_show_owner_ip') && $comment->user_id != 1)) {
                        $ip = pk_get_ip_region_str($comment->comment_author_IP);
                        echo "<span class='mt10' title='IP'><i class='fa-solid fa-location-dot'></i>&nbsp;$ip</span>";
                    }
                }
                
    echo '          </div>
                </div>
            </div>
        </div>';

此代码应替换`inc/fun/comment-ajax.php`中对应代码，注意开头需要`use function donatj\UserAgent\parse_user_agent;`

**Comment by Lvshujun0918** [comment]
评论等级和UA是动态获取的，不显示符合预期

**Comment by jd82k** [comment]
> 评论等级和UA是动态获取的，不显示符合预期

动态获取的没错，ajax提交评论response直接返回包含ua  ip的html就可以了，我代码已经写好了，如上，你直接替换就可以了

**Comment by jd82k** [comment]
这个puock主题前台ajax提交评论后是把后台返回的html渲染到dom，并不是前台直接就将评论文字渲染到dom了，所以是可以将ip以及ua还有平台os显示出来的

**Comment by Lvshujun0918** [comment]
已采纳
